# Generated by Django 4.2.6 on 2023-11-14 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0002_bloco_noticia_delete_image_bloco_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagem',
        ),
    ]
