# Generated by Django 4.2.6 on 2023-11-27 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=500, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=30, null=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsite.noticia')),
            ],
        ),
    ]
