# Generated by Django 4.2.6 on 2023-11-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='desenvolvedor',
            field=models.CharField(default='##', max_length=80),
        ),
        migrations.AddField(
            model_name='noticia',
            name='genero',
            field=models.CharField(default='##', max_length=80),
        ),
        migrations.AddField(
            model_name='noticia',
            name='plataformas',
            field=models.CharField(default='##', max_length=300),
        ),
    ]
