# Generated by Django 4.2.6 on 2023-11-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0003_remove_noticia_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='desenvolvedor',
            field=models.CharField(default='##', max_length=60),
        ),
        migrations.AddField(
            model_name='noticia',
            name='genero',
            field=models.CharField(default='##', max_length=40),
        ),
        migrations.AddField(
            model_name='noticia',
            name='plataformas',
            field=models.CharField(default='##', max_length=300),
        ),
    ]
